### ISSUE TITLE
Splitting up the WRF docker build

### ISSUE THREAD

**Issue by douglowe** [UoMResearchIT/EMEP-docker#1]
The WRF docker is building more than just WRF - so I wonder if we can split some items out? 
https://github.com/UoMResearchIT/EMEP-docker/blob/master/WRF/Dockerfile

* zlib - needed
* libpng - needed
* jasper - needed
* hdf5 - needed
* netcdf - needed
* mpich - needed
* NCEPlibs - move out
* UPP - move out
* ARWpost - move out
* OpenGrADS - move out
* g2ctl - move out
* wgrib2 - perhaps needed later?
* WRF - needed
* WPS - needed (check why 4.3.1 and not 4.3.3?)
* WPSPLUS - needed later, leave out for now
* WPSPLUS 4DVAR - needed later, leave out for now

NCEPlibs, UPP, ARWpost, OpenGrADS, and g2ctl are useful for post-processing WRF data - I don't think they need to be in the WRF/WPS docker though.

wgrib2 is used for working with GRIB-2 data files, but for the basic creation of WRF input files WPS should suffice (and I think, perhaps, wgrib2 is used more for supporting OpenGrADS work?).

WPSPLUS and WPSPLUS 4DVAR will be useful for many users - but aren't needed (yet) for our usecase, as they deal with data assimulation for forecasting. If they cause any issues for building the docker container then leave them out for now.

**Comment by ghost** [comment]
I would also see about adding obsgrid for wrf. 
Then the wrf docker will only have the main components for any wrf build.
